apiVersion: v1
kind: Service
metadata:
  name: {{ include "caldera.fullname" . }}
  labels:
    {{- include "caldera.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhttp
      protocol: TCP
      name: webhttp
  selector:
    {{- include "caldera.selectorLabels" . | nindent 4 }}
